### ISSUE TITLE
Emerging Technologies for Open Government

### ISSUE THREAD

**Issue by philipashlock** [GSA/participate-nap4#9]

**Comment by akarides** [comment]
Isn't this the objective of this entire National Action Plan? I don't understand why this is a particular issue.

**Comment by jstclair-HFT** [comment]
I'd offer Phillip has it as a placeholder. When we reconvene at some point we can review all for redundancy or consolidation.

**Comment by Atomahawk** [comment]
https://github.com/GSA/participate-nap4/issues/3#issuecomment-333683228

**Comment by rebeccawilliams** [comment]
No details included.
